# Generated by Django 4.2 on 2024-06-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="restaurant2_restaur_d07737_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant"], name="restaurant2_restaur_837b66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["status"], name="restaurant2_status_bd17b8_idx"),
        ),
    ]
