# Generated by Django 4.2.4 on 2024-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0002_remove_order_restaurant2_restaur_d07737_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="restaurant2_restaur_837b66_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="restaurant2_status_bd17b8_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "status"], name="restaurant2_restaur_d07737_idx"
            ),
        ),
    ]
