# Generated by Django 4.2.4 on 2024-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant2", "0004_remove_order_restaurant2_restaur_d07737_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["paid"], name="restaurant2_paid_ee7129_idx"),
        ),
    ]
