# Generated by Django 4.2.4 on 2024-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usermodel_is_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_employee_of_restaurant",
            field=models.BooleanField(
                default=False, verbose_name="Employee of Restaurant"
            ),
        ),
    ]
