# Generated by Django 4.2.4 on 2024-03-11 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="etc", max_length=100, verbose_name="Category name"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Category types",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="FilteringModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter", models.CharField(max_length=100, verbose_name="filter")),
                (
                    "option",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Additional explanation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7. Filter product list",
            },
        ),
        migrations.CreateModel(
            name="GoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="product name")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Popular"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.categorymodel",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Product list",
                "db_table": "goods",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel", models.CharField(max_length=20)),
                ("total_prices", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shipping_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="type"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="detail"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "8. Terms and privacy policy",
            },
        ),
        migrations.CreateModel(
            name="StoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Store name")),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="store location"),
                ),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_number",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Company Registration Number",
                    ),
                ),
                (
                    "sub_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Store detailed address",
                    ),
                ),
                (
                    "introduce",
                    models.TextField(
                        blank=True, null=True, verbose_name="introduction"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="seller",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Store list",
                "db_table": "store",
            },
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("star", models.FloatField(default=0, verbose_name="scope")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.goodsmodel",
                        verbose_name="review product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Writer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. Review history",
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="order time"),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.goodsmodel",
                        verbose_name="purchase goods",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="buyer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. Order History",
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitem",
                        to="store.goodsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.goodsmodel",
                        verbose_name="Goods",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Product image list",
                "db_table": "image",
            },
        ),
        migrations.AddField(
            model_name="goodsmodel",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storemodel",
                verbose_name="store",
            ),
        ),
        migrations.CreateModel(
            name="BookmarkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookmark", models.BooleanField(default=True)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.goodsmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bookmark history",
                "db_table": "bookmark",
            },
        ),
    ]
