# Generated by Django 4.2.4 on 2024-03-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=50)),
                ("account_number", models.CharField(max_length=50)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.storemodel",
                        verbose_name="store",
                    ),
                ),
            ],
        ),
    ]
