# Generated by Django 4.2.4 on 2024-03-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.storemodel"
            ),
        ),
    ]
