# Generated by Django 4.2.4 on 2024-03-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_remove_cart_store_cartitem_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemodel",
            name="background_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/",
                verbose_name="background image",
            ),
        ),
    ]
