# Generated by Django 4.2.4 on 2024-03-20 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_storemodel_background_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="store",
        ),
        migrations.RemoveField(
            model_name="order",
            name="store",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
