# Generated by Django 4.2.4 on 2024-03-20 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
