# Generated by Django 4.2.4 on 2024-04-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
