# Generated by Django 5.0.2 on 2024-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_review_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemodel",
            name="logo",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="logo image"
            ),
        ),
    ]
