# Generated by Django 5.0.2 on 2024-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0018_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="china_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lao_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
