# Generated by Django 4.2.4 on 2024-04-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_order_china_url_order_lao_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.storemodel",
                verbose_name="store",
            ),
        ),
    ]
