# Generated by Django 4.2.4 on 2024-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_order_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tel1", models.CharField(max_length=20)),
                ("tel2", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        verbose_name="logo image",
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        verbose_name="background image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
