# Generated by Django 4.2.4 on 2024-04-23 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_webinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinfo",
            options={"verbose_name_plural": "Website Informations"},
        ),
        migrations.AlterModelTable(
            name="webinfo",
            table="WebInfo",
        ),
    ]
