# Generated by Django 5.0.2 on 2024-04-24 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_alter_webinfo_options_alter_webinfo_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storemodel",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="storemodel",
            name="logo",
        ),
    ]
