# Generated by Django 5.0.2 on 2024-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0023_remove_storemodel_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_bill",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
