# Generated by Django 5.0.2 on 2024-04-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0024_order_order_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storemodel",
                verbose_name="store",
            ),
        ),
    ]
