# Generated by Django 4.2.4 on 2024-04-29 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0027_rename_notice_noticemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noticemodel",
            options={"ordering": ("-id",)},
        ),
    ]
