# Generated by Django 4.2.4 on 2024-04-30 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0028_alter_noticemodel_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticemodel",
            name="date",
        ),
        migrations.RemoveField(
            model_name="noticemodel",
            name="detail",
        ),
    ]
