# Generated by Django 4.2.4 on 2024-11-14 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0033_stocked_stockedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsmodel",
            name="stocked_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods",
                to="store.stockedimage",
            ),
        ),
    ]
