# Generated by Django 4.2.4 on 2024-11-14 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0037_alter_goodsmodel_stocked_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsmodel",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="goodsmodel",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="goodsmodel",
            name="stocked_image",
        ),
    ]
