# Generated by Django 4.2.4 on 2024-11-15 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0039_goodsmodel_latitude_goodsmodel_longitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodsmodel",
            old_name="latitude",
            new_name="x_axis",
        ),
        migrations.RenameField(
            model_name="goodsmodel",
            old_name="longitude",
            new_name="y_axis",
        ),
    ]
