# Generated by Django 4.2.4 on 2024-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0040_rename_latitude_goodsmodel_x_axis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="x_axis",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="goodsmodel",
            name="y_axis",
            field=models.JSONField(null=True),
        ),
    ]
