# Generated by Django 4.2.4 on 2024-12-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0041_alter_goodsmodel_x_axis_alter_goodsmodel_y_axis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmodel",
            name="stocked_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="store.stockedimage",
            ),
        ),
        migrations.AlterField(
            model_name="stocked",
            name="point_view",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
