# Generated by Django 4.2.4 on 2025-02-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0043_storebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mode3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="3D Mode Enabled"),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mode_3d",
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3D Mode Settings",
                "db_table": "mode_3d",
            },
        ),
    ]
