# Generated by Django 4.2.4 on 2025-04-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0044_mode3d"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mode3DImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/mode_3d/")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mode_3d_image",
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3D Mode Image",
                "db_table": "mode_3d_image",
            },
        ),
    ]
