# Generated by Django 4.2.4 on 2025-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0045_mode3dimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mode3dimage",
            name="sort_order",
            field=models.IntegerField(default=0, max_length=3, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="mode3dimage",
            unique_together={("store", "sort_order")},
        ),
    ]
