# Generated by Django 4.2.4 on 2025-04-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0047_alter_mode3dimage_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mode3dimage",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
