# Generated by Django 4.2.4 on 2025-04-02 04:41

from django.db import migrations, models

def remove_invalid_position_data(apps, schema_editor):
    Mode3DImage = apps.get_model('store', 'Mode3DImage')
    # ลบข้อมูลที่มี position เป็น 'front' หรือค่าที่ไม่ใช่ตัวเลข
    Mode3DImage.objects.filter(position__isnull=False).exclude(position__regex=r'^\d+$').update(position=None)

def check_position_field(apps, schema_editor):
    # ตรวจสอบว่ามี field position อยู่จริงหรือไม่
    Mode3DImage = apps.get_model('store', 'Mode3DImage')
    if hasattr(Mode3DImage, 'position'):
        # ถ้ามี field position ให้ลบข้อมูลที่ไม่ถูกต้อง
        remove_invalid_position_data(apps, schema_editor)

class Migration(migrations.Migration):
    dependencies = [
        ("store", "0048_alter_mode3dimage_sort_order"),
    ]

    operations = [
        migrations.RunPython(check_position_field),
        migrations.RemoveField(
            model_name='mode3dimage',
            name='position',
        ),
    ]
